[colors]
foreground = "#ffffff"
background = "#190d39"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#190d39"
selection_bg = "#306282"
selection_fg = "#ffffff"

ansi = ["#140a2e", "#812ddb", "#569900", "#b2008b", "#438dbb", "#e028da", "#299ca2", "#8e8b9c"]
brights = ["#190d39", "#812ddb", "#569900", "#b2008b", "#438dbb", "#e028da", "#299ca2", "#ffffff"]

[colors.tab_bar]
inactive_tab_edge = "#22124e"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "#438dbb"
bg_color = "#190d39"

[colors.tab_bar.inactive_tab]
bg_color = "#22124e"
fg_color = "#2a1a55"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#22124e"
fg_color = "#438dbb"

[colors.tab_bar.new_tab_hover]
fg_color = "#22124e"
bg_color = "#438dbb"

[colors.tab_bar.new_tab]
fg_color = "#438dbb"
bg_color = "#191b28"

[metadata]
aliases = []
author = "HabielLau"
name = "Vpanime Girl"