[colors]
foreground = "#635f96"
background = "#d2d0e5"
cursor_bg = "#635f96"
cursor_border = "#635f96"
cursor_fg = "#d2d0e5"
selection_bg = "#f75ce0"
selection_fg = "#635f96"

ansi = ["#dddbeb", "#eb3bd9", "#b9a9f7", "#f0eefa", "#fc3ae0", "#dbaff5", "#417176", "#7574a5"]
brights = ["#d2d0e5", "#eb3bd9", "#b9a9f7", "#f0eefa", "#fc3ae0", "#dbaff5", "#417176", "#635f96"]

[colors.tab_bar]
inactive_tab_edge = "#e0def4"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "${blue}"
bg_color = "#d2d0e5"

[colors.tab_bar.inactive_tab]
bg_color = "#e0def4"
fg_color = "#d2d0e5"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#e0def4"
fg_color = "#fc3ae0"

[colors.tab_bar.new_tab_hover]
fg_color = "#e0def4"
bg_color = "#fc3ae0"

[colors.tab_bar.new_tab]
fg_color = "#fc3ae0"
bg_color = "#191b28"

[metadata]
aliases = []
author = "taylor"
name = "VpAnime Girl Light"