[colors]
foreground = "#cac9dd"
background = "#282248"
cursor_bg = "#cac9dd"
cursor_border = "#cac9dd"
cursor_fg = "#282248"
selection_bg = "#971a87"
selection_fg = "#cac9dd"

ansi = ["#201b3a", "#f146df", "#4c1ca5", "#140a32", "#a80e94", "#55186c", "#7cd1d9", "#abaac9"]
brights = ["#282248", "#f146df", "#4c1ca5", "#140a32", "#a80e94", "#55186c", "#7cd1d9", "#cac9dd"]

[colors.tab_bar]
inactive_tab_edge = "#1c1546"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "${blue}"
bg_color = "#282248"

[colors.tab_bar.inactive_tab]
bg_color = "#1c1546"
fg_color = "#282248"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1c1546"
fg_color = "#a80e94"

[colors.tab_bar.new_tab_hover]
fg_color = "#1c1546"
bg_color = "#a80e94"

[colors.tab_bar.new_tab]
fg_color = "#a80e94"
bg_color = "#191b28"

[metadata]
aliases = []
author = "taylor"
name = "VpAnime Girl"