# vpanime-girl Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0xebe9f9'
    foreground: '0x474747'

  # Normal colors
  normal:
    black:   '0xf1effa'
    red:     '0xa676f1'
    green:   '0x3f7300'
    yellow:  '0xff34cb'
    blue:    '0x336e93'
    magenta: '0xbb20b6'
    cyan:    '0x196b70'
    white:   '0x635f74'

  # Bright colors
  bright:
    black:   '0xebe9f9'
    red:     '0xa676f1'
    green:   '0x3f7300'
    yellow:  '0xff34cb'
    blue:    '0x336e93'
    magenta: '0xbb20b6'
    cyan:    '0x196b70'
    white:   '0x474747'

  indexed_colors:
    - { index: 16, color: '0xcd55fa' }
    - { index: 17, color: '0x9b3ff4' }
    
  