# vpanime-girl Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0xd2d0e5'
    foreground: '0x635f96'

  # Normal colors
  normal:
    black:      '0xdddbeb'
    dkpink:     '0xfc8bec'
    green:      '0x048218'
    purple:     '0xd3cef7'
    pink:       '0xfc44df'
    dkmagenta:  '0xddb2f5'
    cyan:       '0x318189'
    white:      '0x7574a5'

  # Bright colors
  bright:
    black:      '0xd2d0e5'
    dkpink:     '0xfc8bec'
    green:      '0x048218'
    purple:     '0xd3cef7'
    pink:       '0xfc44df'
    dkmagenta:  '0xddb2f5'
    cyan:       '0x318189'
    white:      '0x635f96'

  indexed_colors:
    - { index: 16, color: '0xbfb0f7' }
    - { index: 17, color: '0xfc28f4' }

  