# vpanime-girl Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x190d39'
    foreground: '0xffffff'

  # Normal colors
  normal:
    black:   '0x140a2e'
    red:     '0x812ddb'
    green:   '0x569900'
    yellow:  '0xb2008b'
    blue:    '0x438dbb'
    magenta: '0xe028da'
    cyan:    '0x299ca2'
    white:   '0x8e8b9c'

  # Bright colors
  bright:
    black:   '0x190d39'
    red:     '0x812ddb'
    green:   '0x569900'
    yellow:  '0xb2008b'
    blue:    '0x438dbb'
    magenta: '0xe028da'
    cyan:    '0x299ca2'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xa016c9' }
    - { index: 17, color: '0xa050f5' }
    
  