# vpanime-girl Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x282248'
    foreground: '0xcac9dd'

  # Normal colors
  normal:
    black:      '0x201b3a'
    dkpink:     '0x76086b'
    green:      '0x0cd82e'
    purple:     '0x2a1569'
    pink:       '0xa40e90'
    dkmagenta:  '0x521767'
    cyan:       '0x4dc0cb'
    white:      '0xabaac9'

  # Bright colors
  bright:
    black:      '0x282248'
    dkpink:     '0x76086b'
    green:      '0x0cd82e'
    purple:     '0x2a1569'
    pink:       '0xa40e90'
    dkmagenta:  '0x521767'
    cyan:       '0x4dc0cb'
    white:      '0xcac9dd'

  indexed_colors:
    - { index: 16, color: '0x461998' }
    - { index: 17, color: '0xa60ca0' }

  