# vpanime-girl Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x282248'
    foreground: '0xcac9dd'

  # Normal colors
  normal:
    black:      '0x201b3a'
    dkpink:     '0xf146df'
    green:      '0x0de731'
    purple:     '0x140a32'
    pink:       '0xa80e94'
    dkmagenta:  '0x55186c'
    cyan:       '0x7cd1d9'
    white:      '0xabaac9'

  # Bright colors
  bright:
    black:      '0x282248'
    dkpink:     '0xf146df'
    green:      '0x0de731'
    purple:     '0x140a32'
    pink:       '0xa80e94'
    dkmagenta:  '0x55186c'
    cyan:       '0x7cd1d9'
    white:      '0xcac9dd'

  indexed_colors:
    - { index: 16, color: '0x4c1ca5' }
    - { index: 17, color: '0xf546e3' }

  