[[themes]]
name = "Vpanime Girl Light"
[themes.palette]
background = "#dfdbf7"
foreground = "#635f74"
black = "#ebe9f9"
red = "#a676f1"
green = "#3f7300"
yellow = "#ff34cb"
blue = "#336e93"
magenta = "#bb20b6"
cyan = "#196b70"
white = "#ebe9f9"
bright_black = "#ebe9f9"
bright_red = "#9b3ff4"
bright_green = "#3f7300"
bright_yellow = "#cd55fa"
bright_blue = "#2f81b4"
bright_magenta = "#e139db"
bright_cyan = "#4e99c9"
bright_white = "#474747"
