[[themes]]
name = "Vpanime Girl"
[themes.palette]
background = "#22124e"
foreground = "#8e8b9c"
black = "#190d39"
red = "#812ddb"
green = "#569900"
yellow = "#b2008b"
blue = "#438dbb"
magenta = "#e028da"
cyan = "#299ca2"
white = "#190d39"
bright_black = "#190d39"
bright_red = "#a050f5"
bright_green = "#569900"
bright_yellow = "#a016c9"
bright_blue = "#46b2f5"
bright_magenta = "#f254ec"
bright_cyan = "#306282"
bright_white = "#ffffff"
